### ISSUE TITLE
Implement the "Client" Piece of the "Broker" Workflow

### ISSUE THREAD

**Issue by churay** [LLNL-Collaboration/uiuc2015#10]
The "client" piece of the "broker" workflow (see issue #6 for more information) should be implemented as a simple script that performs the following actions when invoked:
- Establishes an SSH connection with the hard-coded machine that's hosting the "broker" script (see issue #9) as the user that invoked the "client" script.
- Executes the "broker" script to load any connection information saved for the running user.
- Pipes the connection information produced by the "broker" script back to the "client" host.
- Establishes a connection on the "client" host with the "server" host using the connection information received from the "broker."

Once this issue is completed, the "client" script should be capable of grabbing connection information for the current user and using this information to establish an SSH connection with the host running the "server" script.

**Comment by xjrc** [comment]
Added for the February 17 milestone.
