### ISSUE TITLE
Implement the "Server" Piece of the "Broker" Workflow

### ISSUE THREAD

**Issue by churay** [LLNL-Collaboration/uiuc2015#11]
The "server" piece of the "broker" workflow (see issue #6 for more information) should be implemented as a simple script that performs the following actions when invoked:
- Opens a protected communication channel that it will use to communicate with the "client" host and saves the connection information for this channel.
- Establishes an SSH connection with the hard-coded machine that's hosting the "broker" script (see issue #9) as the user that invoked the "server" script.
- Executes the "broker" script to securely save the connection information for the channel established on the "server" host to a file that's exclusive to the running user.
- Waits for the "client" host to connect and prints out a notification message once the connection is established.

Once this issue is completed, the "server" script should be capable of opening a communication channel, publishing the information about connection to this channel using the "broker," and communicating with the "client" after it receives the information it needs from the "broker."

**Comment by xjrc** [comment]
Added for the February 17 milestone.
