### ISSUE TITLE
Implement the "Broker" Piece of the "Broker" Workflow

### ISSUE THREAD

**Issue by churay** [LLNL-Collaboration/uiuc2015#9]
The "broker" piece of the "broker" workflow (see issue #6 for more information) should be implemented as a simple script with the two following capabilities:
- `./broker.py save [cxn-info]`: Saves the given connection information to a read-protected file that can only be accessed by the user that invoked the script.
- `./broker.py load`: Loads and prints any connection information that's available for the user (or an error if no such information exists).

For the first iteration of this script, the "broker" needs to be only capable of transmitting connection information for SSH connections.  Once this issue is completed, the "broker" script should be capable of saving and loading SSH connection information associated with the user executing it.

**Comment by xjrc** [comment]
Added for the February 17 milestone.
